FORMAT: A1

# Verball

API for verbs from different languages with translations and conjugations.


# Group Languages

Resources for the **Languages** of the **Verbs**.


## Language Collection [/languages]

### List All Languages [GET]

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "code": "en",
                "id": "en",
                "name": "english",
                "nativeName": "english",
                "url": "/languages/en",
                "pronouns": {
                    "1s": "I",
                    "1p": "we",
                    "2s": "you",
                    "2p": "you",
                    "3ms": "he",
                    "3fs": "she",
                    "3ns": "it"
                },
                "tenses": [
                    {
                        "name": "simple past",
                        "nativeName": "simple past",
                        "_id": "simplePast"
                    },
                    {
                        "name": "present",
                        "nativeName": "present",
                        "_id": "present"
                    }
                ]
            },
            {
                "code": "de",
                "id": "de",
                "name": "german",
                "nativeName": "deutsch",
                "url": "/languages/de",
                "pronouns": {
                    "1s": "ich",
                    "1p": "wir",
                    "2s": "du",
                    "2p": "ihr",
                    "3ms": "er",
                    "3fs": "sie",
                    "3ns": "es",
                    "form": "Sie"
                },
                "tenses": [
                    {
                        "name": "simple past",
                        "nativeName": "Präteritum",
                        "_id": "simplePast"
                    },
                    {
                        "name": "present",
                        "nativeName": "Präsens",
                        "_id": "present"
                    }

                ]
            }
        ]


### Create a Language [POST]

To create a new **Language** you have `POST` a JSON document including the [ISO 639-1 code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes), the English name and the native name of the language.

+ code (string) - ISO 639-1 code of the language
+ name (string) - English name of the language
+ nativeName (string) - Native name of the language
+ 
+ tenses (array) - Array of tenses
    + name (string) - Name of the tense
    + nativeName (string) - Native name of the tense

+ Request (application/json)

        {
            "code": "fr",
            "name": "French",
            "nativeName": "Français",

            "tenses": [
                {
                  "name": "simple past", 
                  "nativeName": "passé simple"
                },
                {
                  "name": "present", 
                  "nativeName": "présent"
                }
            ]
        }

+ Response 201 (application/json; charset=utf-8)

    + Headers

            Location: /language/fr

    + Body

            {
                "code": "fr",
                "id": "fr",
                "name": "french",
                "nativeName": "français",
                "url": "/languages/fr",
                "tenses": [
                    {
                      "name": "simple past", 
                      "nativeName": "passé simple",
                      "_id": "simplePast"
                    },
                    {
                      "name": "present", 
                      "nativeName": "présent",
                      "_id": "present"
                    }
                ]
            }



## Language [/languages/{language_code}]

+ Parameters
    + language_code: en (string) - ISO 639-1 Code of the Language


### Get a Language [GET]

+ Response 200 (application/json; charset=utf-8)

        {
            "code": "en",
            "id": "en",
            "name": "english",
            "nativeName": "english",
            "url": "/languages/en",
            "pronouns": {
                "1s": "I",
                "1p": "we",
                "2s": "you",
                "2p": "you",
                "3ms": "he",
                "3fs": "she",
                "3ns": "it"
            },
            "tenses": [
                {
                    "name": "simple past",
                    "nativeName": "Präteritum",
                    "_id": "simplePast"
                },
                {
                    "name": "present",
                    "nativeName": "Präsens",
                    "_id": "present"
                }

            ]
        }


### Update a Language [PUT]

+ name (string) - English Name of the Language
+ nativeName (string) - Native Name of the Language

+ Request (application/json)

        {
            "nativeName": "american",
            "pronouns": {
                "2p": "y'all"
            }
        }

+ Response 200 (application/json; charset=utf-8)

    + Headers

            Location: /languages/en

    + Body

            {
                "code": "en",
                "id": "en",
                "name": "english",
                "nativeName": "american",
                "url": "/languages/en",
                "pronouns": {
                    "1s": "I",
                    "1p": "we",
                    "2s": "you",
                    "2p": "y'all",
                    "3ms": "he",
                    "3fs": "she",
                    "3ns": "it"
                },
                "tenses": [
                    {
                        "name": "simple past",
                        "nativeName": "Präteritum",
                        "_id": "simplePast"
                    },
                    {
                        "name": "present",
                        "nativeName": "Präsens",
                        "_id": "present"
                    }

                ]
            }


### Delete a Language [DELETE]

+ Response 204



# Group Verbs

Resources for **Verbs**.


## Verb Collection [/verbs]

### List All Verbs [GET /verbs]

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "infinitive": "go",
                "language": "en",
                "url": "/verbs/en/go",
                "id": "5849da8acb46ec150a090068",
                "conjugations": {
                    "present": {
                        "1s": "go",
                        "2s": "go",
                        "3ms": "goes"
                    }
                }
            },
            {
                "infinitive": "gehen",
                "language": "de",
                "url": "/verbs/de/gehen",
                "id": "5849dfbbfa380e1a36daf91d",
                "conjugations": {
                    "present": {
                        "1s": "gehe",
                        "2s": "gehst",
                        "3ms": "geht"
                    }
                }
            },
            {
                "infinitive": "fahren",
                "language": "de",
                "url": "/verbs/de/fahren",
                "id": "5849eb774a5d2f244f416e6a",
                "conjugations": {
                    "present": {
                        "1s": "fahre",
                        "2s": "fährst",
                        "3ms": "fährt"
                    }
                }
            }
        ]


### List All Verbs of a Language [GET /verbs/{language_code}]

+ Parameters
    + language_code: en (optional, string) - ISO 639-1 Code of the Language

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "infinitive": "go",
                "language": "en",
                "url": "/verbs/en/go",
                "id": "5849da8acb46ec150a090068",
                "conjugations": {
                    "present": {
                        "1s": "go",
                        "2s": "go",
                        "3ms": "goes"
                    }
                }
            }
        ]

### Find All Verbs Matching a Query String [GET /verbs?q={query}]

+ Parameters
    + query: go (optional, string) - Query string for verb infinitive.

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "infinitive": "go",
                "language": "en",
                "url": "/verbs/en/go",
                "id": "5849da8acb46ec150a090068",
                "conjugations": {
                    "present": {
                        "1s": "go",
                        "2s": "go",
                        "3ms": "goes"
                    }
                }
            }
        ]

### Create a Verb [POST /verbs]

+ infinitive (string) - Infinitive of the Verb
+ language (string) - ISO 639-1 Code of the Language

+ Request (application/json; charset=utf-8)

        {
            "infinitive": "fly",
            "language": "en",
            "conjugations": {
                "present": {
                    "1s": "fly",
                    "2s": "fly",
                    "3ms": "flies"
                }
            }
        }

+ Response 201 (application/json; charset=utf-8)

        {
            "infinitive": "fly",
            "language": "en",
            "url": "/verbs/en/fly",
            "id": "5849da8acb46ec150a090068",
            "conjugations": {
                "present": {
                    "1s": "fly",
                    "2s": "fly",
                    "3ms": "flies"
                }
            }
        }


## Verb [/verbs/]

### Get a Verb By ID [GET /verbs/{id}]

+ Parameters
    + id: 5849da8acb46ec150a090068 (optional, string) - ID of the Verb

+ Response 200 (application/json; charset=utf-8)

        {
            "infinitive": "go",
            "language": "en",
            "url": "/verbs/en/go",
            "id": "5849da8acb46ec150a090068",
            "conjugations": {
                "present": {
                    "1s": "go",
                    "2s": "go",
                    "3ms": "goes"
                }
            }
        }


### Get a Verb By Language and Infinitive [GET /verbs/{language_code}/{infinitive}]

+ Parameters
    + language_code: en (string) - ISO 639-1 code of the Language
    + infinitive: go (string) - Infinitive of the Verb

+ Response 200 (application/json; charset=utf-8)

        {
            "infinitive": "go",
            "language": "en",
            "url": "/verbs/en/go",
            "id": "5849da8acb46ec150a090068",
            "conjugations": {
                "present": {
                    "1s": "go",
                    "2s": "go",
                    "3ms": "goes"
                }
            }
        }


### Get Translations of a Verb by Language and Infinitive [GET /verbs/{language_code}/{infinitive}/translations]

+ Parameters
    + language_code: en (string) - ISO 639-1 code of the Language
    + infinitive: go (string) - Infinitive of the Verb

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "infinitive": "gehen",
                "language": "de",
                "url": "/verbs/de/gehen",
                "id": "5849dfbbfa380e1a36daf91d",
                "conjugations": {
                    "present": {
                        "1s": "gehe",
                        "2s": "gehst",
                        "3ms": "geht"
                    }
                }
            }
        ]


### Get Translations of a Verb by ID [GET /verbs/{id}/translations]

+ Parameters
    + id: 5849da8acb46ec150a090068 (string) - ID of the Verb

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "infinitive": "gehen",
                "language": "de",
                "url": "/verbs/de/gehen",
                "id": "5849dfbbfa380e1a36daf91d",
                "conjugations": {
                    "present": {
                        "1s": "gehe",
                        "2s": "gehst",
                        "3ms": "geht"
                    }
                }
            }
        ]


###  Create a Translation of a Verb [POST /verbs/{language_code}/{infinitive}/translations]

+ Parameters
    + language_code: en (string) - ISO 639-1 code of the Language
    + infinitive: go (string) - Infinitive of the Verb

+ Request (application/json; charset=utf-8)

        {
            "infinitive": "hingehen",
            "language": "de",
            "conjugations": {
                "present": {
                    "1s": "gehe hin",
                    "2s": "gehst hin",
                    "3ms": "geht hin"
                }
            }
        }

+ Response 201 (application/json; charset=utf-8)

        [
            {
                "infinitive": "go",
                "language": "en",
                "url": "/verbs/en/go",
                "id": "5849da8acb46ec150a090068",
                "conjugations": {
                    "present": {
                        "1s": "go",
                        "2s": "go",
                        "3ms": "goes"
                    }
                }
            },
            {
                "infinitive": "hingehen",
                "language": "de",
                "url": "/verbs/de/hingehen",
                "id": "584b0ed824a4b9032d2cde1f",
                "conjugations": {
                    "present": {
                        "1s": "gehe hin",
                        "2s": "gehst hin",
                        "3ms": "geht hin"
                    }
                }
            }
        ]


###  Link Translations of two Verbs [POST /verbs/{language_code}/{infinitive}/translations/{translation_language_code}]

+ Parameters
    + language_code: en (string) - ISO 639-1 code of the Language
    + infinitive: go (string) - Infinitive of the Verb
    + translation_language_code: de (string) - ISO 639-1 code of the Translation Language

+ Request with ID (application/json; charset=utf-8)

        {
            "id": "5849eb774a5d2f244f416e6a"
        }

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "infinitive": "go",
                "language": "en",
                "url": "/verbs/en/go",
                "id": "5849da8acb46ec150a090068",
                "conjugations": {
                    "present": {
                        "1s": "go",
                        "2s": "go",
                        "3ms": "goes"
                    }
                }
            },
            {
                "infinitive": "fahren",
                "language": "de",
                "url": "/verbs/de/fahren",
                "id": "5849eb774a5d2f244f416e6a",
                "conjugations": {
                    "present": {
                        "1s": "fahre",
                        "2s": "fährst",
                        "3ms": "fährt"
                    }
                }
            }
        ]

+ Request with Infinitive (application/json; charset=utf-8)

        {
            "infinitive": "fahren"
        }

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "infinitive": "go",
                "language": "en",
                "url": "/verbs/en/go",
                "id": "5849da8acb46ec150a090068",
                "conjugations": {
                    "present": {
                        "1s": "go",
                        "2s": "go",
                        "3ms": "goes"
                    }
                }
            },
            {
                "infinitive": "fahren",
                "language": "de",
                "url": "/verbs/de/fahren",
                "id": "5849eb774a5d2f244f416e6a",
                "conjugations": {
                    "present": {
                        "1s": "fahre",
                        "2s": "fährst",
                        "3ms": "fährt"
                    }
                }
            }
        ]


### Update Verb by ID [PUT /verbs/{id}]

+ Parameters
    + id: 5849da8acb46ec150a090068 (string) - ID of the Verb

+ Request (application/json; charset=utf-8)

        {
            "infinitive": "Walk",
            "conjugations": {
                "present": {
                    "1s": "walk",
                    "2s": "walk",
                    "3ms": "walks"
                }
            }
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "infinitive": "walk",
            "language": "de",
            "url": "/verbs/de/walk",
            "id": "5849dfbbfa380e1a36daf91d",
            "conjugations": {
                "present": {
                    "1s": "walk",
                    "2s": "walk",
                    "3ms": "walks"
                }
            }
        }


### Update Verb by Language Code and Infinitive [PUT /verbs/{language_code}/{infinitive}]

+ Parameters
    + language_code: en (string) - ISO 639-1 code of the Language
    + infinitive: go (string) - Infinitive of the Verb

+ Request (application/json; charset=utf-8)

        {
            "infinitive": "Walk",
            "conjugations": {
                "present": {
                    "1s": "walk",
                    "2s": "walk",
                    "3ms": "walk"
                }
            }
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "infinitive": "walk",
            "language": "en",
            "url": "/verbs/en/walk",
            "id": "5849dfbbfa380e1a36daf91d",
            "conjugations": {
                "present": {
                    "1s": "walk",
                    "2s": "walk",
                    "3ms": "walks"
                }
            }
        }


### Delete Verb by ID [DELETE /verbs/{id}]

+ Parameters
    + id: 5849da8acb46ec150a090068 (string) - ID of the Verb

+ Response 204


### Delete Verb by Language Code and Infinitive [DELETE /verbs/{language_code}/{infinitive}]

+ Parameters
    + language_code: en (string) - ISO 639-1 code of the Language
    + infinitive: go (string) - Infinitive of the Verb

+ Response 204
